version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  serverless-framework: circleci/serverless-framework@2.0
executors:
  default:
    docker:
      - image: 'cimg/node:14.18.2'
    environment:
      AWS_REGION: 'us-west-2'
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: WEB IDENTITY PROFILE
          role-arn: CIRCLE_CI_WEB_IDENTITY_ROLE
          role-session-name: circleci-session
          web-identity-token: CIRCLE_OIDC_TOKEN
workflows:
  aws-cli:
    jobs:
      - deploy:
          context: aws